---
output:
  pdf_document: default
  html_document: default
---

---
title: "Task 3.1 Unsupervised learning"
output:
  html_notebook: default
  pdf_document: default
---
# From Alexandra Schwaiger

##used library

```{r}
rm(list=ls())
require("clusterCrit")
require("gplots")
require("fpc")
```


## Load data and get an overview
Our dataset contains primary numeric features


```{r}

food_data <- read.csv("C:/Users/PC/Desktop/Modul12/food.csv", row.names =1)
fds <- scale(food_data)

```

## clustering

```{r}
best_k <- 0
best_silu <- -Inf
for (k in 2:5) {
  kmc <- kmeans(fds, centers =k)
  ci <- intCriteria(fds,kmc$cluster, "Silhouette")
  silhouette_value <- ci$silhouette
   cat("Silhouette coefficient for k =", k, ":", silhouette_value, "\n")
  if (silhouette_value > best_silu) {
    best_k <- k
    best_silu <- silhouette_value
    }
}
  
cat("\nFinal selected number of clusters:", best_k, "\n")
```


## PCA
```{r}
  pca <- princomp(fds)
  data_red <- pca$scores[,1:2]
  data_red <- data_red * -1
  plot(data_red[,"Comp.1"], data_red[,"Comp.2"], col=kmc$cluster)
  text(data_red[,"Comp.1"], data_red[,"Comp.2"] - 0.1, labels=row.names(fds), cex=0.5)


summary(pca)

```

##Hirarchical clustering
```{r}
hcf <- hclust(dist(fds))
plot(hcf)
```


```{r}
heatmap.2(fds, scale ="none")
```

## density based clustering
```{r}
dbc <- dbscan(fds, eps = 3)
clus <- dbc$cluster
clus
  plot(data_red[,"Comp.1"], data_red[,"Comp.2"], col=clus)
  text(data_red[,"Comp.1"], data_red[,"Comp.2"], labels=row.names(fds), cex=0.5)
```

